

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - push
  - deploy

build_job:
  stage: build
  script:
    - echo "Building project...."

test_job:
  stage: test
  script:
    - echo "Testing build...."

push_job:
  stage: push
  script:
    - echo "Pushing build....."

deploy_job:
  stage: deploy
  script:
    - echo "Deploying build....."
    