stages:    
  - build
  - test
  - push
  - deploy

variables:
  DEPLOY_ENV: "production"
  MY_VAR: "just keep leanring."

build_job:
  stage: build
  script:
    - echo "Building $CI_PROJECT_NAME project...."

build_test_job:
  stage: test
  script:
    - echo "Testing $CI_COMMIT_AUTHOR build...."
    - echo "Testing $CI_COMMIT_AUTHOR build reports logs" > artifacts/test_job/build_test_job.log
    - mkdir -p artifacts/test_job/
  artifacts:
    paths:
      - artifacts/test_job/
    expire_in: 1 week

quality_test_job:
  stage: test
  script:
    - echo "Quality Assurance Testing...."

prod_test_job:
  stage: test
  script:
    - echo "Production Grade Testing...."

docker_push_job:
  stage: push
  script:
    - echo "Log in to docker hub with username $DOCKER_HUB_USERNAME password $DOCKER_HUB_PASSWORD"
    - echo "Pushing to Docker hub....."

ec2_push_job:
  stage: push
  script:
    - echo "Pushing to EC2...."
    - echo "Pushing EC2 report for team members" > artifacts/push_job/ec2_push_job.log
    - mkdir -p artifacts/push_job/
  artifacts:
    paths:
      - artifacts/push_job/
    expire_in: 2 week

stagging_deploy_job:
  stage: deploy
  script:
    - echo "Stagging Deploy...."

production_deploy_job:
  stage: deploy
  script:
    - echo "Production $CI_RUNNER_ID Deploy...."
    - echo "Artifacts production deployment report logs $CI_JOB_STAGE" > artifacts/deploy_job/production_deploy_job.log
    - mkdir -p artifacts/deploy_job/
  artifacts:
    paths:
      - artifacts/deploy_job/
    expire_in: 3 week