stages:    
  - build
  - test
  - push
  - deploy

build_job:
  stage: build
  script:
    - echo "Building project...."

build_test_job:
  stage: test
  script:
    - echo "Testing build...."

quality_test_job:
  stage: test
  script:
    - echo "Quality Assurance Testing...."

prod_test_job:
  stage: test
  script:
    - echo "Production Grade Testing...."

docker_push_job:
  stage: push
  script:
    - echo "Pushing to Docker hub....."

ec2_push_job:
  stage: push
  script:
    - echo "Pushing to EC2...."

deploy_job:
  stage: deploy
  script:
    - echo "Deploying build....."
